#!/bin/bash

# Get dependencies first
flutter/bin/flutter pub get

# Create assets directory if it doesn't exist
mkdir -p assets

# Create .env file in assets from Vercel environment variables
cat > assets/.env << EOL
FIREBASE_API_KEY=$FIREBASE_API_KEY
FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL
FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
FIREBASE_APP_ID=$FIREBASE_APP_ID
FIREBASE_MEASUREMENT_ID=$FIREBASE_MEASUREMENT_ID
PUSH_NOTIFICATION_TYPE=$PUSH_NOTIFICATION_TYPE
PUSH_NOTIFICATION_PROJECT_ID=$PUSH_NOTIFICATION_PROJECT_ID
PUSH_NOTIFICATION_PRIVATE_KEY_ID=$PUSH_NOTIFICATION_PRIVATE_KEY_ID
PUSH_NOTIFICATION_PRIVATE_KEY=$PUSH_NOTIFICATION_PRIVATE_KEY
PUSH_NOTIFICATION_CLIENT_EMAIL=$PUSH_NOTIFICATION_CLIENT_EMAIL
PUSH_NOTIFICATION_CLIENT_ID=$PUSH_NOTIFICATION_CLIENT_ID
PUSH_NOTIFICATION_AUTH_URI=$PUSH_NOTIFICATION_AUTH_URI
PUSH_NOTIFICATION_TOKEN_URI=$PUSH_NOTIFICATION_TOKEN_URI
PUSH_NOTIFICATION_AUTH_PROVIDER_X509_CERT_URL=$PUSH_NOTIFICATION_AUTH_PROVIDER_X509_CERT_URL
PUSH_NOTIFICATION_CLIENT_X509_CERT_URL=$PUSH_NOTIFICATION_CLIENT_X509_CERT_URL
PUSH_NOTIFICATION_UNIVERSE_DOMAIN=$PUSH_NOTIFICATION_UNIVERSE_DOMAIN
GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY
EOL

# Verify the file exists
echo "✅ Created assets/.env:"
ls -la assets/.env
head -3 assets/.env

# Build the Flutter web app
flutter/bin/flutter build web --release